// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("b_quant_offset"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("has_b_frames"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("i_quant_factor"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("i_quant_offset"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("lumi_masking"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("temporal_cplx_masking"));
}
