// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("pre_dia_size"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("me_subpel_quality"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("me_range"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("slice_flags"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("mb_decision"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("intra_matrix"));
}
