// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("seek_preroll"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("chroma_intra_matrix"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("dump_separator"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("codec_whitelist"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("properties"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("coded_side_data"));
}
