// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("subtitle_header"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("subtitle_header_size"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("initial_padding"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("sw_pix_fmt"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("codec_descriptor"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("pts_correction_num_faulty_pts"));
}
