// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("lowres"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("thread_count"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("thread_type"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("active_thread_type"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(AVCodecContext.execute.class, "apply", constants$20.const$4);
}
