// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("rc_max_available_vbv_use"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("rc_min_vbv_overflow_use"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("rc_initial_buffer_occupancy"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("trellis"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("stats_out"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("stats_in"));
}
