// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final VarHandle const$0 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("frame_size"));
    static final VarHandle const$1 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("initial_padding"));
    static final VarHandle const$2 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("trailing_padding"));
    static final VarHandle const$3 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("seek_preroll"));
    static final VarHandle const$4 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("coded_side_data"));
    static final VarHandle const$5 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("nb_coded_side_data"));
}


