// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("apply_cropping"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("extra_hw_frames"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("discard_damaged_percentage"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("max_samples"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("export_side_data"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(AVCodecContext.get_encode_buffer.class, "apply", constants$14.const$4);
}
