// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("max_qdiff"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("rc_buffer_size"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("rc_override_count"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("rc_override"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("rc_max_rate"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("rc_min_rate"));
}
