// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("me_sub_cmp"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("mb_cmp"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("ildct_cmp"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("dia_size"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("last_predictor_count"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("me_pre_cmp"));
}
