// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("colorspace"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("color_range"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("chroma_sample_location"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("slices"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("field_order"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("sample_rate"));
}
