// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final VarHandle const$0 = constants$3.const$3.varHandle(MemoryLayout.PathElement.groupElement("channel_layout"));
    static final VarHandle const$1 = constants$3.const$3.varHandle(MemoryLayout.PathElement.groupElement("channels"));
    static final VarHandle const$2 = constants$3.const$3.varHandle(MemoryLayout.PathElement.groupElement("sample_rate"));
    static final VarHandle const$3 = constants$3.const$3.varHandle(MemoryLayout.PathElement.groupElement("block_align"));
    static final VarHandle const$4 = constants$3.const$3.varHandle(MemoryLayout.PathElement.groupElement("frame_size"));
    static final VarHandle const$5 = constants$3.const$3.varHandle(MemoryLayout.PathElement.groupElement("initial_padding"));
}


