// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("get_encode_buffer"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("frame_num"));
}
