// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("priv_class"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("profiles"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("wrapper_name"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("ch_layouts"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buf"),
        JAVA_LONG.withName("pts"),
        JAVA_LONG.withName("dts"),
        RuntimeHelper.POINTER.withName("data"),
        JAVA_INT.withName("size"),
        JAVA_INT.withName("stream_index"),
        JAVA_INT.withName("flags"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("side_data"),
        JAVA_INT.withName("side_data_elems"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("duration"),
        JAVA_LONG.withName("pos"),
        RuntimeHelper.POINTER.withName("opaque"),
        RuntimeHelper.POINTER.withName("opaque_ref"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("num"),
            JAVA_INT.withName("den")
        ).withName("time_base")
    ).withName("AVPacket");
    static final VarHandle const$5 = constants$2.const$4.varHandle(MemoryLayout.PathElement.groupElement("buf"));
}


