// Generated by jextract

package org.ffmpeg.libavcodec;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("codec_tag"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("priv_data"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("internal"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("opaque"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("bit_rate"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("bit_rate_tolerance"));
}
