// Generated by jextract

package org.ffmpeg.libavformat;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("seek2any"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("flush_packets"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("probe_score"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("format_probesize"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("codec_whitelist"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("format_whitelist"));
}
