// Generated by jextract

package org.ffmpeg.libavformat;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("event_flags"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("max_ts_probe"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("avoid_negative_ts"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("ts_id"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("audio_preload"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("max_chunk_duration"));
}
