// Generated by jextract

package org.ffmpeg.libavformat;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("ctx_flags"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("nb_streams"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("streams"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("url"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("start_time"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("duration"));
}
