// Generated by jextract

package org.ffmpeg.libavformat;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("bit_rate"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("packet_size"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("max_delay"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("flags"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("probesize"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("max_analyze_duration"));
}
