// Generated by jextract

package org.ffmpeg.libavformat;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("start_time_realtime"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("fps_probe_size"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("error_recognition"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("debug"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("max_interleave_delta"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("strict_std_compliance"));
}
