// Generated by jextract

package org.ffmpeg.libavformat;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final VarHandle const$0 = constants$0.const$0.varHandle(PathElement.groupElement("opaque"));
    static final VarHandle const$1 = constants$0.const$0.varHandle(PathElement.groupElement("control_message_cb"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(PathElement.groupElement("output_ts_offset"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(PathElement.groupElement("dump_separator"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(PathElement.groupElement("data_codec_id"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(PathElement.groupElement("protocol_whitelist"));
}
