// Generated by jextract

package org.ffmpeg.libavutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final VarHandle const$0 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("top_field_first"));
    static final VarHandle const$1 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("palette_has_changed"));
    static final VarHandle const$2 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("reordered_opaque"));
    static final VarHandle const$3 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("sample_rate"));
    static final VarHandle const$4 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("channel_layout"));
    static final VarHandle const$5 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("extended_buf"));
}


