// Generated by jextract

package org.ffmpeg.libavutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final VarHandle const$0 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("color_trc"));
    static final VarHandle const$1 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("colorspace"));
    static final VarHandle const$2 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("chroma_location"));
    static final VarHandle const$3 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("best_effort_timestamp"));
    static final VarHandle const$4 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("pkt_pos"));
    static final VarHandle const$5 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("pkt_duration"));
}


