// Generated by jextract

package org.ffmpeg.libavutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final UnionLayout const$0 = MemoryLayout.unionLayout(
        JAVA_LONG.withName("mask"),
        RuntimeHelper.POINTER.withName("map")
    ).withName("");
    static final VarHandle const$1 = constants$1.const$0.varHandle(MemoryLayout.PathElement.groupElement("mask"));
    static final VarHandle const$2 = constants$1.const$0.varHandle(MemoryLayout.PathElement.groupElement("map"));
    static final VarHandle const$3 = constants$0.const$3.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "av_channel_layout_from_mask",
        constants$1.const$4
    );
}


