// Generated by jextract

package org.ffmpeg.libavutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("num"),
        JAVA_INT.withName("den")
    ).withName("AVRational");
    static final VarHandle const$1 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("num"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("den"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("order"),
        JAVA_INT.withName("nb_channels"),
        MemoryLayout.unionLayout(
            JAVA_LONG.withName("mask"),
            RuntimeHelper.POINTER.withName("map")
        ).withName("u"),
        RuntimeHelper.POINTER.withName("opaque")
    ).withName("AVChannelLayout");
    static final VarHandle const$4 = constants$0.const$3.varHandle(MemoryLayout.PathElement.groupElement("order"));
    static final VarHandle const$5 = constants$0.const$3.varHandle(MemoryLayout.PathElement.groupElement("nb_channels"));
}


