// Generated by jextract

package org.ffmpeg.libavutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "av_frame_alloc",
        constants$11.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "av_frame_free",
        constants$2.const$2
    );
}


