// Generated by jextract

package org.ffmpeg.libavutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final VarHandle const$0 = constants$0.const$5.varHandle(MemoryLayout.PathElement.groupElement("order"));
    static final VarHandle const$1 = constants$0.const$5.varHandle(MemoryLayout.PathElement.groupElement("nb_channels"));
    static final UnionLayout const$2 = MemoryLayout.unionLayout(
        JAVA_LONG.withName("mask"),
        RuntimeHelper.POINTER.withName("map")
    ).withName("");
    static final VarHandle const$3 = constants$1.const$2.varHandle(MemoryLayout.PathElement.groupElement("mask"));
    static final VarHandle const$4 = constants$1.const$2.varHandle(MemoryLayout.PathElement.groupElement("map"));
    static final VarHandle const$5 = constants$0.const$5.varHandle(MemoryLayout.PathElement.groupElement("opaque"));
}


