// Generated by jextract

package org.ffmpeg.libavutil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final VarHandle const$0 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("crop_top"));
    static final VarHandle const$1 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("crop_bottom"));
    static final VarHandle const$2 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("crop_left"));
    static final VarHandle const$3 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("crop_right"));
    static final VarHandle const$4 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("private_ref"));
    static final VarHandle const$5 = constants$3.const$2.varHandle(MemoryLayout.PathElement.groupElement("duration"));
}


